### ISSUE TITLE
Weighted/Guided refinement criterion

### ISSUE THREAD

**Issue by takafusui** [ORNL/TASMANIAN#295]
Tasmanian has already provided the customized refinement criterion and had the scale correction argument in the local version of the setSurplusRefinement() function; however, the python interface of this seems to be missing. I highly appreciate if you provide this function in python so that we can customize a refinement criterion depending on the specific needs of our applications.

**Comment by mkstoyanov** [comment]
I'll include that.

**Comment by takafusui** [comment]
Thank you! I am looking forward to testing it soon.

**Comment by mkstoyanov** [comment]
Functionality added in PR 304 and available in the development version.

@takafusui you can now test the guided refinement and let me know if you see any issues.

**Comment by takafusui** [comment]
Thank you for your development! I will test this function and will inform you about my findings in the future.

**Comment by takafusui** [comment]
I have carefully tested it, and so far, it stabilizes and reduces the number of grid points in each refinement step. Thank you again for your implementation!

I have a question about the guided refinement in Tasmanian.
In the User's Guide p. 17 2.8 Local Polynomial Grids: Adaptive refinement, you divide the absolute value of hierarchical surplus |s|  by the maximum value of |f(x)|, instead of merely employing the refinement strategy |s| > epsilon.

May I ask you reasons why you normalize the hierarchical surplus |s| by the maximum value of the function? If I want to cancel your original deviation, should I use the guided refinement, or have you already implemented an easy way to do so?

**Comment by mkstoyanov** [comment]
One of the early applications of Tasmanian involved combustion engine simulations, the grid had multiple outputs including temperature in Kelvin of magnitude a few hundred and chemicals (e.g., fuel) in KMol units of magnitude `O(1.E-6)`. The difference in magnitude between the two was about 9 orders, it made absolutely no sense to use a single global epsilon. Thus, Tasmanian normalizes each output so that all have a scale of (0, 1) and epsilon is interpreted as *relative error tolerance*.

Since the scale simply multiplies the ratio |s| / max|f(x)|, setting uniform correction of max|f(x)| will effectively switch to the unscaled version of the refinement |s| > \epsilon. Note that the max is computed from the loaded values, i.e., the raw-data given to Tasmanian and not the maximum of the surrogate.

**Comment by takafusui** [comment]
Thank you for your prompt replay. It makes sense to me. Indeed in my application, the grid has multiple outputs, including KKT multipliers. KKT multipliers take a very small number (1e-6) when the associated constraints are not binding; thus, it seems to be a better option for me to divide hierarchical surpluses by their maximum output values to normalize them between 0 to 1.

**Comment by mkstoyanov** [comment]
The issue was opened for a missing part of the Python interface, this has already been resolved.

Feel free to open a new issue for bugs or other comments.
