### ISSUE TITLE
Python interface and PyTorch.tensor

### ISSUE THREAD

**Issue by takafusui** [ORNL/TASMANIAN#489]
Hi,

I use the Tasmanian library to interpolate highly non-linear functions in the contest of dynamic programming.
Since an optimizer requires Jacobian, I use the PyTorch's automatic gradient function, but there is a conflict with the python interface of Tasmanian because the interface assumes numpy.
For instance, in the following snippet:
```python
policy_plus.evaluate(_stateplus)
```
Since `_stateplus` is a tensor variable, the Tasmanian claims the following error.
```python
AttributeError: 'Tensor' object has no attribute '__array_interface__'
```
Do you have some hacks to have the tensor variable as the argument of the `evaluate` method?'

Tasmanian: version 7.0
Python 3.7

Thank you in advance.

**Comment by mkstoyanov** [comment]
Tasmanian is not a python package, Tasmanian is written in C++ and has wrappers that can be used through Python. If the tensor variables have a way to be cast as raw c-style arrays, e.g., similar to
```
numpy.ctypeslib.as_ctypes(x)
```
then those can be passed to the C wrappers that will then move over to C++ and everything will be OK.

I doubt this would work in the context of automatic differentiation. AD usually requires access to the code in order to compute the gradients by the application of the chain rule, I don't think Python can read and work with C++ code.

Right now, you can use finite difference to make several calls to evaluate and approximate the gradients. Since the surrogate is already an approximation, this method should work OK.

For the future, we have ideas of putting a Jacobian method in Tasmanian, but it would require lots of tricky code.

**Comment by takafusui** [comment]
Thank you for the explanation. I am fully convinced by your comments and will approximate some Jacobian with finite-difference.
I would like to close the issue and thank you again!
