### ISSUE TITLE
Interpolation results from 'grid.evaluate()' differ significantly after Anaconda upgrading

### ISSUE THREAD

**Issue by songqingsongsong** [ORNL/TASMANIAN#549]
Hi there,

Apology in advance since I know I am vague about this question. 

I didn't upgrade my Jupyter notebook since November, 2019. In the past few weeks, I have been using TASMANIAN sparse grid to solve a time iteration problem. I used the interpolation function like introduced in this example (https://ornl.github.io/TASMANIAN/stable/group__TasmanianSGExamples4.html). I expect at least some positive numbers, but in many cases, interpolation is negative. After I upgrade Anaconda to the latest version, this issue is fixed magically. 

I reckon the source code of  'grid.evaluate()' performs differently with support of the 'latest' and 'not-so-latest' Jupyter Notebook. Is there any chance that I can get hints to look at specific libraries in Python to figure out why? If needed, I can send my code files. I know it is like a mission impossible. Thanks in advance for your patience and time.

Regards,
Qingsong

**Comment by mkstoyanov** [comment]
Are you sure the issue isn't because of different `x` being given as input to `grid.evaluate(x)`. Jupiter can be tricky with block getting evaluated out of order or some other confusion like that.

Tasmanian evaluate is simple, gets the numpy-array and uses `numpy.ctypeslib.as_ctypes(x)` to extract the C-pointer to contiguous memory and passes it to the C++ library.

The only other difference that can come from an Anaconda upgrade is the BLAS library. To check is the library makes the difference, you can check if `evaluateThreadSafe()` gives different result.

**Comment by songqingsongsong** [comment]
I see. Thanks for your information and I will look into it. I feel much more confident now!

**Comment by mkstoyanov** [comment]
Start a new issue if you still see a problem.
