### ISSUE TITLE
Tests fail in gcc 11.2.0

### ISSUE THREAD

**Issue by tribe01** [ORNL/TASMANIAN#654]
All the tests fail while building with gcc-11.2.0 Here are the cmake options used. Same options works well for 9.3.0 

`cmake -D CMAKE_INSTALL_PREFIX:PATH=/home/TASMANIAN/install_prefix -D Tasmanian_ENABLE_PYTHON:BOOL=ON -D CMAKE_BUILD_TYPE:STRING=Release ..
`

**Comment by mkstoyanov** [comment]
That's odd. I'll try to reproduce tomorrow, in the mean time can you pass in the output of:
```
./SparseGrids/gridtest
```
It should show an error if the problem is as simple as missing to link to some system library or if it is mixing the libstdc and libstc++ versions at runtime.

**Comment by mkstoyanov** [comment]
@tribe01 Just tested with gcc 11.2 on Ubuntu 21.10 and had no issues, so it is not as simple as the compiler.

I would need more information in order to help.

Which system are you using? Is this your own laptop? it's hard to imagine a large cluster has already migrated to gcc 11.2. 

Have you tried to compiler and run a "hello world" program?

**Comment by mkstoyanov** [comment]
Stale, reopen if the problem is still there.
